# Generated by Django 5.0.4 on 2024-05-13 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vista_administrador', '0001_initial'),
        ('vista_usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sucursal',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='vista_administrador.sucursal'),
        ),
    ]
