# Generated by Django 5.0.4 on 2024-05-29 20:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vista_usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='es_privada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='parte_oferta',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='imagenes',
            field=models.ManyToManyField(related_name='publicaciones', to='vista_usuario.imagen', validators=[django.core.validators.MaxValueValidator(5, 'Solo se permiten hasta 5 imágenes.')]),
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
                ('fecha_intercambio', models.DateField()),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_como_base', to='vista_usuario.publicacion')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_como_oferta', to='vista_usuario.publicacion')),
            ],
        ),
    ]
