# Generated by Django 5.0.4 on 2024-06-14 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vista_usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='campo_temporal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
