# Generated by Django 5.0.4 on 2024-05-04 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vista_usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nombre',
        ),
    ]
