# Generated by Django 5.0.4 on 2024-04-29 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vista_usuario', '0002_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='autor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='vista_usuario.usuario'),
        ),
    ]
