# Generated by Django 5.0.4 on 2024-05-13 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vista_administrador', '0001_initial'),
        ('vista_usuario', '0002_user_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sucursal',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='vista_administrador.sucursal'),
        ),
    ]
