# Generated by Django 5.0.4 on 2024-05-29 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vista_administrador', '0001_initial'),
        ('vista_usuario', '0002_publicacion_es_privada_publicacion_parte_oferta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intercambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
                ('fecha_intercambio', models.DateField()),
                ('estado', models.CharField(choices=[('realizado', 'Intercambio Realizado'), ('cancelado', 'Intercambio Cancelado'), ('cancelado_ausente', 'Cancelado por Ausencia'), ('pendiente', 'Intercambio Pendiente')], default='pendiente', max_length=20)),
                ('base', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base_intercambios', to='vista_usuario.publicacion')),
                ('ofer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oferta_intercambios', to='vista_usuario.publicacion')),
                ('sucursal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vista_administrador.sucursal')),
                ('usuario_ausente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
