# Generated by Django 5.0.4 on 2024-06-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vista_usuario', '0003_alter_oferta_options_remove_oferta_campo_temporal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='estado',
            field=models.CharField(choices=[('ESPERANDO RESPUESTA', 'ESPERANDO RESPUESTA'), ('RECHAZADO', 'RECHAZADO'), ('ACEPTADO', 'ACEPTADO')], default='ESPERANDO RESPUESTA', max_length=20),
        ),
    ]
