# Generated by Django 5.0.4 on 2024-06-01 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vista_administrador', '0001_initial'),
        ('vista_usuario', '0003_intercambio'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='usuario_ofertante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_hechas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='oferta',
            name='usuario_recibe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_recibidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='sucursal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vista_administrador.sucursal'),
        ),
    ]
