# Generated by Django 5.0.4 on 2024-05-02 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vista_usuario', '0004_remove_usuario_apellido_remove_usuario_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='autor',
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='categoria',
            field=models.CharField(choices=[('Electricidad', 'Electricidad'), ('Ferretería general', 'Ferretería general'), ('Construcción', 'Construcción'), ('Herramientas', 'Herramientas'), ('Jardinería', 'Jardinería'), ('Protección personal', 'Protección personal')], max_length=50),
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='imagenes_publicaciones/')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='vista_usuario.publicacion')),
            ],
        ),
    ]
