# Generated by Django 5.0.4 on 2024-06-23 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vista_usuario', '0004_alter_oferta_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='intercambio',
            name='ganancia',
            field=models.IntegerField(default=0),
        ),
    ]
