# Generated by Django 5.0.4 on 2024-05-02 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vista_usuario', '0006_remove_publicacion_horario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='nombre_producto',
            new_name='sucursal',
        ),
        migrations.RenameField(
            model_name='publicacion',
            old_name='sucursal_a_retirar',
            new_name='titulo',
        ),
    ]
