# Generated by Django 5.0.4 on 2024-05-03 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vista_usuario', '0007_rename_nombre_producto_publicacion_sucursal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(default='nulu', max_length=30),
            preserve_default=False,
        ),
    ]
